#include "BasicComptonEvent.hh"
#include "VEventReconstructionAlgorithm.hh"
#include "HitTreeIOWithInitialInfo.hh"
#include "ComptonEventTreeIOWithInitialInfo.hh"

namespace comptonsoft {
class ConstructDetector;
class ConstructDetectorForSimulation;
class VCSModule;
class CSHitCollection;
class ConstructChannelMap;
class DefineBadChannel;
class SetNoiseLevel;
class SelectHit;
class AnalyzeHit;
class MakeDetectorHit;
class MakeRawHit;
class MakeDetectorHitTR;
class DetectorGroupManager;
class EventSelection;
class EventReconstruction;
class HXIEventSelection;
class SaveData;
class ReadDataFile;
class ReadDataFile_VME3;
class ReadDataFile_SpW2;
class ReadDataFile_NT;
class ReadDataFile_NB0;
class CorrectPHA;
class RecalculateEPI;
class CalculatePedestal;
class InitialConditionFilter;
class RecalculateSimulationNoise;
class ComptonModeFilter;
class SelectFullDeposit;
class ComptonEventFilter;
class SelectTime;
class WriteHitTree;
class ReadHitTree;
class ReadRawHitTree;
class ReadDetectorHitTree;
class WriteComptonEventTree;
class ReadComptonEventTree;
class HistPHA;
class EnergySpectrum;
class PlaneWaveRectanglePrimaryGen;
class IsotropicPrimaryGen;
class PrimaryGenInVolume;
class NucleusPrimaryGen;
class NucleusPrimaryGenInVolume;
class AHRayTracingPrimaryGen;
class SimXPrimaryGen;
class AHRadiationBackgroundPrimaryGen;
class RDPickUpData;
class ActivationPickUpData;
class AHStandardPickUpData;
class KillStepPickUpData;
class MaterialSamplePickUpData;
class ScatteringPickUpData;
class AHStandardANLPhysicsList;
class SimXIF;
class GenerateSimXEvent;
class OutputSimXPrimaries;
class AssignG4CopyNumber;
class InitialParticleTree;
class DumpMass;
}
