general:
    efield_v_cm: 500
    temperature_k: 87.0
light: 
    waveform_analysis: average
    light_channels: [4, 6, 5, 7]
    light_gamma_thr_mV: 20.0
    light_cosmic_thr_mV: 250.0
    delay_counts: 60
    pre_roi_window_us: 1.0
    post_roi_window_us: 5.0
    pre_roi_peak_thr_mV: 15.0
    post_roi_peak_thr_mV: 15.0
charge: 
    adu_min: 18.0
    adu_max: 1000.0
    pix_min: 1
    pix_max: 3
    circ_thr: 10.0
    spread_thr: 7.0
    drift_time_max_us: 70.0
    noise_th: 20.0
    circ_min_hits: 4
    circ_min_ratio: 0.2
    exclude_pix:  #list or str(peripheral)
        0: peripheral 
        1: peripheral 
        2: peripheral 
        3: [peripheral]
calibration: 
    energy: 
        gain_info_file: subproducts/gainFuncParam3d.hdf5
        q_to_kev_spline_file: subproducts/QvsEkeV_spline.root
        factor_energy: 1.0
        max_time_us: 67.0
        tp_channel: 17
        ccal: 8
    position:
        anode_pos_z_cm: 5.0
