general:
    efield_v_cm: 500
    temperature_k: 87.0
    drift_time_max_us: 70.0
clustering:
    data_group_list:
        - test

    data_root_dir: data/tpc_data
    outdir_parent: products/eventfile
    gain_tp_file: products/testpulse_data.csv
    gain_cache_seconds: 60.0
    output_flush_entries: 1000
    quicklook_event_types: [gamma,error,other,cosmic,pileup,timeup] # error/other/gamma/cosmic/pileup/timeup
    quicklook_num_hits: -1 # Negative values disable hit-count selection.
    quicklook_save_waveforms: false
light: 
    event_selection_mode: veto_only
    waveform_analysis: average
    general_analysis_channels: [5,6,7]
    pileup_analysis_channels: [4]
    light_gamma_thr_mV: 20.0
    light_cosmic_thr_mV: 250.0
    pre_roi_window_us: 0.2
    post_roi_window_us: 5.0
    out_roi_peak_thr_mV: 15.0
    transimpedance_feedback_resistance_ohm: 3200.0
    output_impedance_ohm: 50.0
charge: 
    noise_th_kev: 150.0
    clustering_pix_range: [1, 3]
    spread_thr_kev: 100.0
    cross_fec_merge_drift_time_tolerance_us: 3.0
    core_exclude_pix:
        0: [0, 63]
        1: [0, 63]
        2: [0, 63]
        3: [0, 63]
calibration: 
    energy: 
        gain_info_file: ../subproducts/gainFuncParam3d.hdf5
        tp_channel: 17
        ccal: 8
    position:
        anode_pos_z_cm: 5.0
